require_relative 'adapters/multitenant_redis_adapter'
require_relative 'adapters/multitenant_directory_adapter'
require_relative 'adapters/single_redis_adapter'
require_relative 'adapters/single_file_adapter'
require_relative 'adapters/database_yml_adapter'
require_relative 'adapters/env_variables_adapter'
require_relative 'adapters/scoped'
